### ISSUE TITLE
Computer is not Turing complete

### ISSUE THREAD

**Issue by InputBlackBoxOutput** [skerr92/oak832128#1]
Hi,

I cannot think of a way I can NOT the values in a register using the current ISA.  To implement all kinds of digital logic we need the **NOT** operation to accompany **AND** or **OR**

Thanks!

**Comment by skerr92** [comment]
Hi there!

Thank you for the feedback! :) I’m currently reworking the instruction set to be more Turing complete. I plan to make the changes later this evening or later on this week. I’ll update this issue once I’ve done that. In the meantime, if you have any other suggestions please feel free to file them under this issue.

-Seth

**Comment by skerr92** [comment]
Added NOT instruction here: https://github.com/skerr92/oak832128/commit/ada402108927ea856772fd6b93c8e18eb16bc204
